package com.example;

public  class Main {
    public static void main(String[] args) {
        System.out.println("Demostración de tipos de datos primitivos en Java:");
        TiposDeDatosPrimitivos.demostrarEnteros();
        System.out.println("-------------------------------");
        TiposDeDatosPrimitivos.demostrarFlotantes();
        System.out.println("-------------------------------");
        TiposDeDatosPrimitivos.demostrarCaracteres();
        System.out.println("-------------------------------");
        TiposDeDatosPrimitivos.demostrarBooleanos();
        System.out.println("-------------------------------");
        TiposDeDatosPrimitivos.demostrarValoresPordeFecto();
        System.out.println("-------------------------------");
        System.out.println("\nConversion de tipos:");
        ConversionDeTipos.demostrarCastingImplicito();
        System.out.println("-------------------------------");
        ConversionDeTipos.demostrarCastingExplicito();
        System.out.println("-------------------------------");
        ConversionDeTipos.demostrarProblemasDePrecision();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de variables y constantes en Java:");
        VariablesYConstantes.demostrarDeclaracionAsignacion();
        System.out.println("-------------------------------");
        VariablesYConstantes.demostrarConvencionesNombres();
        System.out.println("-------------------------------");
        VariablesYConstantes.demostrarConstantes();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de operadores en Java:");
        Operadores.demostrarAritmeticos();
        System.out.println("-------------------------------");
        Operadores.demostrarIncrementoDecremento();
        System.out.println("-------------------------------");
        Operadores.demostrarRelacionales();
        System.out.println("-------------------------------");
        Operadores.demostrarLogicos();
        System.out.println("-------------------------------");
        Operadores.demostrarAsignacionCompuesta();
        System.out.println("-------------------------------");
        Operadores.demostrarOperadorTernario();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de entrada de datos en Java:");
        EntradaDeDatos.leerVariosTipos();
        System.out.println("-------------------------------");
        EntradaDeDatos.manejarSaltoDeLineaPendiente();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de estructuras condicionales en Java:");
        EstructurasCondicionales.ejemploIf();
        System.out.println("-------------------------------");
        EstructurasCondicionales.ejemploIfElse();
        System.out.println("-------------------------------");
        EstructurasCondicionales.ejemploIfElseIfElse();
        System.out.println("-------------------------------");
        EstructurasCondicionales.ejemploSwitch();
        System.out.println("-------------------------------");
        EstructurasCondicionales.ejemploSwitchExpression();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de estructuras de repetición en Java:");
        EstructurasDeRepeticion.ejemploWhile();
        System.out.println("-------------------------------");
        EstructurasDeRepeticion.ejemploDoWhile();
        System.out.println("-------------------------------");
        EstructurasDeRepeticion.ejemploForClasico();
        System.out.println("-------------------------------");
        EstructurasDeRepeticion.ejemploForAnidado();
        System.out.println("-------------------------------");
        EstructurasDeRepeticion.ejemploBreakContinue();
        System.out.println("-------------------------------");
        EstructurasDeRepeticion.ejemploDeEtiquetas();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de métodos estáticos simples en Java:");
        MetodosEstaticosSimples.ejemploDeclaracionLlamada();
        System.out.println("-------------------------------");
        MetodosEstaticosSimples.ejemploPasoParametros("Hola, este es un mensaje de ejemplo", 42);
        System.out.println("-------------------------------");
        int resultadoSuma = MetodosEstaticosSimples.ejemploRetornoValores(10, 20);
        System.out.println("Resultado de la suma: " + resultadoSuma);
        System.out.println("-------------------------------\n Sobrecarga de métodos estáticos:");
        MetodosEstaticosSimples.ejemploSobrecarga();
        MetodosEstaticosSimples.ejemploSobrecarga(100);
        MetodosEstaticosSimples.ejemploSobrecarga("Texto de ejemplo", 200);
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de arreglos unidimensionales en Java:");
        ArreglosUnidimensionales.declararCrearInicializar();
        System.out.println("-------------------------------");
        ArreglosUnidimensionales.mostrarLongitud();
        System.out.println("-------------------------------");
        ArreglosUnidimensionales.recorrerConForClasico();
        System.out.println("-------------------------------");
        ArreglosUnidimensionales.recorrerConForEach();
        System.out.println("-------------------------------");
        ArreglosUnidimensionales.arrayComoParametroYRetorno(new int[]{1, 2, 3, 4, 5});
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de arreglos bidimensionales en Java:");
        ArreglosBidimensionales.declararCrearMatrices();
        System.out.println("-------------------------------");
        ArreglosBidimensionales.recorrerMatriz();
        System.out.println("-------------------------------");
        ArreglosBidimensionales.ejemploUsosTipicos();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de manipulación de cadenas en Java:");
        ManipulacionCadenas.demostrarConcatenacion();
        System.out.println("-------------------------------");
        ManipulacionCadenas.demostrarMetodosUtiles();
        System.out.println("-------------------------------");
        ManipulacionCadenas.demostrarInmutabilidad();
        System.out.println("-------------------------------");
        ManipulacionCadenas.usarStringBuilder();
        System.out.println("-------------------------------");
        System.out.println("\nDemostración de manejo básico de excepciones en Java:");
        ManejoBasicoExcepciones.ejemploTryCatchDivision();
        System.out.println("-------------------------------");
        ManejoBasicoExcepciones.ejemploTryCatchInput();
        System.out.println("-------------------------------");
        ManejoBasicoExcepciones.ejemploBloqueFinally();
        System.out.println("-------------------------------");
        ManejoBasicoExcepciones.evitarCierrePrograma();
 
        

    }
    
}
